"""
Generate synthetic 'near-duplicate' patient records for the identity-resolution
demo, by cloning real patients from the demo subset with controlled field
variations (typo'd name, matching DOB/gender).

Read-only against the database — only SELECTs existing patient rows.
Synthetic clones are never inserted anywhere; they exist only in the
output files this script writes.

Output:
  scripts/demo_data/synthetic_duplicates.json
  scripts/demo_data/synthetic_duplicates.md
"""

import sys
import json
import uuid
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import os
from dotenv import load_dotenv
import psycopg2
from psycopg2.extras import RealDictCursor

from app.services.identity_resolution import match_score

load_dotenv()

OUTPUT_DIR = Path(__file__).resolve().parent / "demo_data"

# (source patient_id, variation description, field to alter, new value)
VARIATIONS = [
    (
        "de7bdc23-9140-c119-268f-36fe8ddaab44",
        "Truncated first name (typo — dropped trailing character)",
        "first_name",
        lambda v: v[:-1],
    ),
    (
        "4c77f24d-765d-edf6-a7d7-bb1d14801f1b",
        "Transposed digits in first name (typo)",
        "first_name",
        lambda v: v[:-3] + v[-2] + v[-3] + v[-1],
    ),
    (
        "299e68be-4e57-a106-3b8a-5e44df196f2a",
        "Common surname misspelling (Johnston -> Johnson)",
        "last_name",
        lambda v: v.replace("Johnston", "Johnson"),
    ),
]


def fetch_patient(cur, patient_id: str) -> dict:
    cur.execute(
        "SELECT patient_id, first_name, last_name, gender, birth_date FROM patients WHERE patient_id = %s",
        (patient_id,),
    )
    row = cur.fetchone()
    if not row:
        raise ValueError(f"Patient {patient_id} not found")
    return dict(row)


def make_clone(original: dict, field: str, transform) -> dict:
    clone = dict(original)
    clone["patient_id"] = f"synthetic-{uuid.uuid4()}"
    clone[field] = transform(original[field])
    clone["birth_date"] = str(original["birth_date"])
    return clone


def build_comparisons() -> list[dict]:
    conn = psycopg2.connect(os.environ["DATABASE_URL"])
    cur = conn.cursor(cursor_factory=RealDictCursor)

    comparisons = []
    for source_id, description, field, transform in VARIATIONS:
        original = fetch_patient(cur, source_id)
        original["birth_date"] = str(original["birth_date"])
        synthetic = make_clone(original, field, transform)

        altered_fields = [f for f in ("first_name", "last_name", "gender", "birth_date")
                           if original[f] != synthetic[f]]

        score = match_score(original, synthetic)

        comparisons.append({
            "variation": description,
            "original": original,
            "synthetic_clone": synthetic,
            "altered_fields": altered_fields,
            "match_score": round(score, 4),
            "would_flag_at_0.85": score >= 0.85,
        })

    cur.close()
    conn.close()
    return comparisons


def write_json(comparisons: list[dict]) -> Path:
    path = OUTPUT_DIR / "synthetic_duplicates.json"
    path.write_text(json.dumps(comparisons, indent=2), encoding="utf-8")
    return path


def write_markdown(comparisons: list[dict]) -> Path:
    lines = ["# Synthetic Near-Duplicate Patients — Identity Resolution Demo", ""]
    lines.append(
        "Generated by `scripts/generate_synthetic_duplicates.py`. These synthetic "
        "clones are **not** written to the database — they exist only in this file "
        "and the accompanying JSON, for use in the demo script."
    )
    lines.append("")

    for i, comp in enumerate(comparisons, start=1):
        original = comp["original"]
        synthetic = comp["synthetic_clone"]
        lines.append(f"## Pair {i}: {comp['variation']}")
        lines.append("")
        lines.append("| Field | Original | Synthetic Clone | Altered? |")
        lines.append("|---|---|---|---|")
        for field in ("patient_id", "first_name", "last_name", "gender", "birth_date"):
            altered = "yes" if field in comp["altered_fields"] else ""
            lines.append(f"| {field} | {original[field]} | {synthetic[field]} | {altered} |")
        lines.append("")
        lines.append(f"**match_score: {comp['match_score']}** "
                      f"({'>= 0.85 — would be flagged' if comp['would_flag_at_0.85'] else '< 0.85 — would NOT be flagged'})")
        lines.append("")

    path = OUTPUT_DIR / "synthetic_duplicates.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    comparisons = build_comparisons()
    json_path = write_json(comparisons)
    md_path = write_markdown(comparisons)
    print(f"Wrote {len(comparisons)} comparisons to:")
    print(f"  {json_path}")
    print(f"  {md_path}")


if __name__ == "__main__":
    main()
