"""
Insert the synthetic near-duplicate patients (generated by
generate_synthetic_duplicates.py) into the patients table as real rows.

This touches ONLY the patients table — a plain INSERT of patient_id,
first_name, last_name, gender, birth_date. It does not write to concepts,
patient_concepts, processing_status, or agent_runs, and does not invoke
Agent 1 or any classification logic.
"""

import sys
import json
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import os
from dotenv import load_dotenv
from sqlalchemy import text

from app.database import engine

load_dotenv()

JSON_PATH = Path(__file__).resolve().parent / "demo_data" / "synthetic_duplicates.json"


def main():
    comparisons = json.loads(JSON_PATH.read_text(encoding="utf-8"))

    with engine.begin() as conn:
        for comp in comparisons:
            clone = comp["synthetic_clone"]
            conn.execute(text("""
                INSERT INTO patients (patient_id, first_name, last_name, gender, birth_date)
                VALUES (:patient_id, :first_name, :last_name, :gender, :birth_date)
                ON CONFLICT (patient_id) DO NOTHING
            """), clone)
            print(f"Inserted {clone['patient_id']} ({clone['first_name']} {clone['last_name']})")


if __name__ == "__main__":
    main()
